# MySQL Configuration
spring.datasource.url=jdbc: db url
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Email SMTP Configuration
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Custom Settings
app.geofence.radius-km=0.5
app.tutor-emails={ 'roll no':'email address', 'roll no':'email address' }
