# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/od_attendance_db?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Email SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vengi006sct@gmail.com
spring.mail.password=csbhnyxoielxffgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Custom Settings
app.geofence.radius-km=0.5
app.tutor-emails={ '23bit':'pathaivengadesh@gmail.com', '24BIT1':'vengadeshd23bit161@skasc.ac.in' , '23bit':'dharmav47sct@gmail.com' }